name: LostAgain
version: '${version}'
main: com.suzunayui.lostagain.LostAgain
api-version: '1.21'
author: Yui
description: A treasure-map-style navigation item for players who tend to get lost

commands:
  lostagain:
    description: Get a lost-again map item
    usage: /<command>
    aliases: [la, maigo]

permissions:
  lostagain.use:
    description: Allows using LostAgain command
    default: true
